import { Link, type Href, router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { getFavorites, removeFavorite } from "@/services/api";
import type { FavoriteItem } from "@/types/api";

export default function FavoriteScreen() {
  const [items, setItems] = useState<FavoriteItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); setItems((await getFavorites()).data); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Không thể tải phim yêu thích."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const remove = async (movieId: number) => { try { await removeFavorite(movieId); setItems(current => current.filter(item => item.movie.id !== movieId)); } catch (removeError) { setError(removeError instanceof Error ? removeError.message : "Không thể bỏ yêu thích."); } };
  return <View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>← Quay lại</Text></Pressable><Text style={styles.title}>Phim yêu thích</Text><View style={styles.spacer} /></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color="#FF526F" /></View> : error && items.length === 0 ? <View style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Thử lại</Text></Pressable></View> : <FlatList data={items} keyExtractor={item => String(item.id)} contentContainerStyle={items.length ? styles.list : styles.emptyList} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor="#FF526F" />} ListHeaderComponent={error ? <Text style={styles.inlineError}>{error}</Text> : null} ListEmptyComponent={<View style={styles.center}><Text style={styles.emptyIcon}>♡</Text><Text style={styles.emptyTitle}>Chưa có phim yêu thích</Text><Text style={styles.emptyText}>Nhấn biểu tượng trái tim trong trang chi tiết phim.</Text><Link href="/movies" style={styles.retry}>Khám phá phim</Link></View>} renderItem={({ item }) => <View style={styles.card}>{item.movie.posterUrl ? <Image source={{ uri: item.movie.posterUrl }} style={styles.poster} /> : <View style={[styles.poster, styles.placeholder]}><Text style={styles.placeholderText}>🎬</Text></View>}<View style={styles.info}><Link href={`/movies/${item.movie.id}` as Href} style={styles.movie}>{item.movie.title}</Link><Text style={styles.meta}>{item.movie.durationMinutes} phút · {new Date(`${item.movie.releaseDate}T00:00:00`).toLocaleDateString("vi-VN")}</Text><Pressable onPress={() => void remove(item.movie.id)}><Text style={styles.remove}>♥ Bỏ yêu thích</Text></Pressable></View></View>} />}</View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, paddingTop: 54, backgroundColor: "#0D0F17" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingBottom: 18 }, back: { color: "#FF8198", fontSize: 11, fontWeight: "800" }, title: { color: "#FFFFFF", fontSize: 20, fontWeight: "900" }, spacer: { width: 55 }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 }, list: { padding: 20, gap: 12, paddingBottom: 40 }, emptyList: { flexGrow: 1 }, card: { flexDirection: "row", overflow: "hidden", borderRadius: 17, backgroundColor: "#191B27", borderWidth: 1, borderColor: "#292C3A" }, poster: { width: 92, height: 132 }, placeholder: { alignItems: "center", justifyContent: "center", backgroundColor: "#3D1730" }, placeholderText: { fontSize: 28 }, info: { flex: 1, justifyContent: "center", padding: 15 }, movie: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, meta: { marginTop: 7, color: "#969AAA", fontSize: 11 }, remove: { marginTop: 18, color: "#FF8198", fontSize: 11, fontWeight: "800" }, error: { color: "#FF8599", textAlign: "center" }, inlineError: { marginBottom: 12, color: "#FF8599", textAlign: "center" }, retry: { marginTop: 15, color: "#FF7089", fontWeight: "800" }, emptyIcon: { color: "#FF7089", fontSize: 48 }, emptyTitle: { marginTop: 12, color: "#FFFFFF", fontSize: 18, fontWeight: "900" }, emptyText: { marginTop: 7, color: "#8F94A7", textAlign: "center" },
});
