import { type Href, router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { getNotifications, markAllNotificationsRead, markNotificationRead } from "@/services/api";
import type { AppNotification } from "@/types/api";

const dateTime = (value: string) => new Date(value).toLocaleString("vi-VN", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });

export default function NotificationScreen() {
  const [items, setItems] = useState<AppNotification[]>([]);
  const [unread, setUnread] = useState(0);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); const result = await getNotifications(); setItems(result.data); setUnread(result.meta.unread); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Không thể tải thông báo."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const open = async (item: AppNotification) => { if (!item.isRead) { await markNotificationRead(item.id); setItems(current => current.map(value => value.id === item.id ? { ...value, isRead: true } : value)); setUnread(current => Math.max(0, current - 1)); } if (item.bookingId) router.push((item.type === "BOOKING_CONFIRMED" ? `/tickets/${item.bookingId}` : `/bookings/${item.bookingId}`) as Href); };
  const readAll = async () => { await markAllNotificationsRead(); setItems(current => current.map(item => ({ ...item, isRead: true }))); setUnread(0); };
  return <View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>← Quay lại</Text></Pressable><Text style={styles.title}>Thông báo</Text><Pressable disabled={unread === 0} onPress={() => void readAll()}><Text style={[styles.readAll, unread === 0 && styles.disabled]}>Đọc tất cả</Text></Pressable></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color="#FF526F" /></View> : error ? <View style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Thử lại</Text></Pressable></View> : <FlatList data={items} keyExtractor={item => String(item.id)} contentContainerStyle={items.length ? styles.list : styles.emptyList} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor="#FF526F" />} ListEmptyComponent={<View style={styles.center}><Text style={styles.emptyTitle}>Chưa có thông báo</Text><Text style={styles.emptyText}>Thông tin về vé sẽ xuất hiện tại đây.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => void open(item)} style={[styles.card, !item.isRead && styles.unreadCard]}><View style={styles.icon}><Text>{item.type === "BOOKING_CONFIRMED" ? "🎟️" : item.type === "SHOWTIME_REMINDER" ? "⏰" : "🔔"}</Text></View><View style={styles.content}><View style={styles.row}><Text style={styles.itemTitle}>{item.title}</Text>{!item.isRead && <View style={styles.dot} />}</View><Text style={styles.body}>{item.body}</Text><Text style={styles.time}>{dateTime(item.createdAt)}</Text></View></Pressable>} />}</View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, paddingTop: 54, backgroundColor: "#0D0F17" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingBottom: 18 }, back: { color: "#FF8198", fontSize: 11, fontWeight: "800" }, title: { color: "#FFFFFF", fontSize: 20, fontWeight: "900" }, readAll: { color: "#FF8198", fontSize: 10, fontWeight: "800" }, disabled: { color: "#5E6271" }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 }, list: { padding: 20, gap: 10, paddingBottom: 40 }, emptyList: { flexGrow: 1 }, card: { flexDirection: "row", gap: 12, padding: 16, borderRadius: 16, backgroundColor: "#171924", borderWidth: 1, borderColor: "#262936" }, unreadCard: { backgroundColor: "#231B28", borderColor: "#5A2940" }, icon: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#2A2D3A" }, content: { flex: 1 }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, itemTitle: { flex: 1, color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#FF526F" }, body: { marginTop: 5, color: "#AEB2C0", fontSize: 11, lineHeight: 17 }, time: { marginTop: 8, color: "#6F7485", fontSize: 9 }, error: { color: "#FF8599", textAlign: "center" }, retry: { marginTop: 14, color: "#FF7089", fontWeight: "800" }, emptyTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" }, emptyText: { marginTop: 7, color: "#8F94A7" },
});
