import { Link, type Href, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ApiError, applyBookingVoucher, getBooking, getConcessions, getTicket, getVouchers, payBookingMock, releaseHold, removeBookingVoucher, submitBooking, updateBookingConcessions } from "@/services/api";
import type { BookingDetails, ConcessionProduct, Ticket, Voucher } from "@/types/api";

const money = (value: string) => `${Number(value).toLocaleString("vi-VN")}đ`;
const dateTime = (value: string) => new Date(value).toLocaleString("vi-VN", { weekday: "long", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });

export default function BookingScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const bookingId = Number(id);
  const [booking, setBooking] = useState<BookingDetails | null>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [remaining, setRemaining] = useState(0);
  const [products, setProducts] = useState<ConcessionProduct[]>([]);
  const [quantities, setQuantities] = useState<Record<number, number>>({});
  const [concessionsDirty, setConcessionsDirty] = useState(false);
  const [vouchers, setVouchers] = useState<Voucher[]>([]);
  const [voucherInput, setVoucherInput] = useState("");
  const [paymentMessage, setPaymentMessage] = useState<string | null>(null);
  const [ticket, setTicket] = useState<Ticket | null>(null);

  const load = useCallback(async () => {
    if (!Number.isInteger(bookingId) || bookingId <= 0) { setError("Mã đơn không hợp lệ."); setLoading(false); return; }
    try { setError(null); const [nextBooking, nextProducts, nextVouchers] = await Promise.all([getBooking(bookingId), getConcessions(), getVouchers()]); setBooking(nextBooking); setProducts(nextProducts); setVouchers(nextVouchers); setVoucherInput(nextBooking.voucher?.code ?? ""); setQuantities(Object.fromEntries(nextBooking.concessions.map(item => [item.productId, item.quantity]))); setConcessionsDirty(false); setTicket(nextBooking.status === "CONFIRMED" ? await getTicket(bookingId) : null); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Không thể tải đơn đặt vé."); }
    finally { setLoading(false); }
  }, [bookingId]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    if (!booking || booking.status === "CANCELLED" || booking.status === "EXPIRED" || booking.status === "CONFIRMED") return;
    const tick = () => { const seconds = Math.max(0, Math.ceil((new Date(booking.expiresAt).getTime() - Date.now()) / 1000)); setRemaining(seconds); if (seconds === 0) void load(); };
    tick(); const timer = setInterval(tick, 1000); return () => clearInterval(timer);
  }, [booking, load]);

  const selectionItems = () => Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([productId, quantity]) => ({ productId: Number(productId), quantity }));
  const persistConcessions = async () => { const next = await updateBookingConcessions(bookingId, selectionItems()); setBooking(next); setVoucherInput(next.voucher?.code ?? ""); setConcessionsDirty(false); return next; };
  const saveConcessions = async () => { try { setSubmitting(true); setError(null); await persistConcessions(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Không thể cập nhật bắp nước."); } finally { setSubmitting(false); } };
  const changeQuantity = (productId: number, delta: number) => { setQuantities(current => ({ ...current, [productId]: Math.max(0, Math.min(10, (current[productId] ?? 0) + delta)) })); setConcessionsDirty(true); };
  const applyVoucher = async () => { if (!voucherInput.trim()) { setError("Vui lòng nhập mã voucher."); return; } try { setSubmitting(true); setError(null); if (concessionsDirty) await persistConcessions(); const next = await applyBookingVoucher(bookingId, voucherInput); setBooking(next); setVoucherInput(next.voucher?.code ?? ""); } catch (voucherError) { setError(voucherError instanceof Error ? voucherError.message : "Không thể áp dụng voucher."); } finally { setSubmitting(false); } };
  const removeVoucher = async () => { try { setSubmitting(true); setError(null); const next = await removeBookingVoucher(bookingId); setBooking(next); setVoucherInput(""); } catch (voucherError) { setError(voucherError instanceof Error ? voucherError.message : "Không thể gỡ voucher."); } finally { setSubmitting(false); } };
  const submit = async () => { try { setSubmitting(true); setError(null); if (concessionsDirty) await persistConcessions(); setBooking(await submitBooking(bookingId)); } catch (submitError) { setError(submitError instanceof ApiError ? submitError.message : "Không thể xác nhận đơn."); await load(); } finally { setSubmitting(false); } };
  const pay = async (outcome: "SUCCESS" | "FAILURE" | "CANCEL") => { try { setSubmitting(true); setError(null); setPaymentMessage(null); const result = await payBookingMock(bookingId, outcome); if (result.payment.status === "SUCCEEDED") { setPaymentMessage("Thanh toán thành công."); await load(); } else setPaymentMessage(result.payment.failureReason ?? "Giao dịch chưa thành công."); } catch (paymentError) { setError(paymentError instanceof Error ? paymentError.message : "Không thể xử lý thanh toán."); await load(); } finally { setSubmitting(false); } };
  const cancel = async () => { try { setSubmitting(true); setError(null); await releaseHold(bookingId); await load(); } catch (cancelError) { setError(cancelError instanceof Error ? cancelError.message : "Không thể hủy đơn."); } finally { setSubmitting(false); } };

  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#FF526F" /><Text style={styles.muted}>Đang tải đơn đặt vé...</Text></View>;
  if (!booking) return <View style={styles.center}><Text style={styles.title}>Không tải được đơn</Text><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Thử lại</Text></Pressable></View>;
  const active = booking.status === "PENDING" || booking.status === "AWAITING_PAYMENT";

  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <Text style={styles.eyebrow}>BƯỚC 4 / 4</Text><Text style={styles.title}>Xác nhận đặt vé</Text>
    <View style={styles.card}><Text style={styles.movie}>{booking.movie.title}</Text><Text style={styles.meta}>{booking.cinema.name} · {booking.room.name}</Text><Text style={styles.meta}>{dateTime(booking.showtime.startsAt)}</Text><Text style={styles.address}>{booking.cinema.address}, {booking.cinema.city}</Text></View>
    <View style={styles.card}><Text style={styles.sectionTitle}>Ghế đã chọn</Text><Text style={styles.seats}>{booking.seats.map(seat => seat.label).join(", ")}</Text>{booking.seats.map(seat => <View key={seat.id} style={styles.row}><Text style={styles.rowText}>Ghế {seat.label}</Text><Text style={styles.rowText}>{money(seat.price)}</Text></View>)}</View>
    {booking.status === "PENDING" && <View style={styles.card}><Text style={styles.sectionTitle}>Bắp nước</Text><Text style={styles.optional}>Không bắt buộc · Chọn tối đa 10 phần mỗi loại</Text>{products.map(product => <View key={product.id} style={styles.productRow}><View style={styles.productInfo}><Text style={styles.productName}>{product.name}</Text><Text style={styles.productDescription}>{product.description}</Text><Text style={styles.productPrice}>{money(product.price)}</Text></View><View style={styles.quantity}><Pressable disabled={(quantities[product.id] ?? 0) === 0} onPress={() => changeQuantity(product.id, -1)} style={styles.quantityButton}><Text style={styles.quantityButtonText}>−</Text></Pressable><Text style={styles.quantityValue}>{quantities[product.id] ?? 0}</Text><Pressable disabled={(quantities[product.id] ?? 0) >= 10} onPress={() => changeQuantity(product.id, 1)} style={styles.quantityButton}><Text style={styles.quantityButtonText}>+</Text></Pressable></View></View>)}{concessionsDirty && <Pressable disabled={submitting} onPress={() => void saveConcessions()} style={styles.saveFood}><Text style={styles.saveFoodText}>Cập nhật bắp nước</Text></Pressable>}</View>}
    {booking.status !== "PENDING" && booking.concessions.length > 0 && <View style={styles.card}><Text style={styles.sectionTitle}>Bắp nước đã chọn</Text>{booking.concessions.map(item => <View key={item.id} style={styles.priceRow}><Text style={styles.priceLabel}>{item.name} × {item.quantity}</Text><Text style={styles.priceValue}>{money(item.lineTotal)}</Text></View>)}</View>}
    {booking.status === "PENDING" && <View style={styles.card}><Text style={styles.sectionTitle}>Voucher</Text>{booking.voucher ? <View style={styles.appliedVoucher}><View style={styles.productInfo}><Text style={styles.voucherCode}>{booking.voucher.code}</Text><Text style={styles.productDescription}>{booking.voucher.name}</Text></View><Pressable disabled={submitting} onPress={() => void removeVoucher()}><Text style={styles.removeVoucher}>Gỡ mã</Text></Pressable></View> : <><View style={styles.voucherForm}><TextInput value={voucherInput} onChangeText={setVoucherInput} autoCapitalize="characters" placeholder="Nhập mã voucher" placeholderTextColor="#707587" style={styles.voucherInput} /><Pressable disabled={submitting} onPress={() => void applyVoucher()} style={styles.applyVoucher}><Text style={styles.applyVoucherText}>Áp dụng</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.voucherSuggestions}>{vouchers.map(voucher => <Pressable key={voucher.id} onPress={() => setVoucherInput(voucher.code)} style={styles.voucherChip}><Text style={styles.voucherChipCode}>{voucher.code}</Text><Text style={styles.voucherChipHint}>Từ {money(voucher.minOrderAmount)}</Text></Pressable>)}</ScrollView></>}</View>}
    {booking.status !== "PENDING" && booking.voucher && <View style={styles.card}><Text style={styles.sectionTitle}>Voucher đã áp dụng</Text><Text style={styles.voucherCode}>{booking.voucher.code} · {booking.voucher.name}</Text></View>}
    <View style={styles.card}><Text style={styles.sectionTitle}>Chi tiết thanh toán</Text><View style={styles.priceRow}><Text style={styles.priceLabel}>Tiền ghế</Text><Text style={styles.priceValue}>{money(booking.pricing.seatSubtotal)}</Text></View><View style={styles.priceRow}><Text style={styles.priceLabel}>Phí dịch vụ ({booking.seats.length} × 5.000đ)</Text><Text style={styles.priceValue}>{money(booking.pricing.serviceFee)}</Text></View>{Number(booking.pricing.concessionSubtotal) > 0 && <View style={styles.priceRow}><Text style={styles.priceLabel}>Bắp nước</Text><Text style={styles.priceValue}>{money(booking.pricing.concessionSubtotal)}</Text></View>}{Number(booking.pricing.discountAmount) > 0 && <View style={styles.priceRow}><Text style={styles.priceLabel}>Giảm giá</Text><Text style={styles.discount}>−{money(booking.pricing.discountAmount)}</Text></View>}<View style={styles.totalCard}><Text style={styles.totalLabel}>Tổng thanh toán</Text><Text style={styles.total}>{money(booking.pricing.totalAmount)}</Text></View></View>
    {active && <View style={styles.timer}><Text style={styles.timerLabel}>{booking.status === "PENDING" ? "Thời gian giữ ghế" : "Thời gian thanh toán"}</Text><Text style={styles.timerValue}>{String(Math.floor(remaining / 60)).padStart(2, "0")}:{String(remaining % 60).padStart(2, "0")}</Text></View>}
    {booking.status === "PENDING" && <Pressable disabled={submitting} onPress={() => void submit()} style={styles.primary}>{submitting ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.primaryText}>{concessionsDirty ? "Lưu và xác nhận đặt vé" : "Xác nhận đặt vé"}</Text>}</Pressable>}
    {booking.status === "AWAITING_PAYMENT" && <View style={styles.success}><Text style={styles.successTitle}>Đơn đã được tạo</Text><Text style={styles.successText}>Mã đơn {booking.code}{"\n"}Trạng thái: Đang chờ thanh toán</Text></View>}
    {booking.status === "AWAITING_PAYMENT" && <View style={styles.card}><Text style={styles.sectionTitle}>Thanh toán thử nghiệm</Text><Text style={styles.optional}>Số tiền: {money(booking.pricing.totalAmount)}</Text><Pressable disabled={submitting} onPress={() => void pay("SUCCESS")} style={styles.primary}>{submitting ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.primaryText}>Mô phỏng thành công</Text>}</Pressable><View style={styles.mockActions}><Pressable disabled={submitting} onPress={() => void pay("FAILURE")} style={styles.mockSecondary}><Text style={styles.mockSecondaryText}>Thất bại</Text></Pressable><Pressable disabled={submitting} onPress={() => void pay("CANCEL")} style={styles.mockSecondary}><Text style={styles.mockSecondaryText}>Hủy giao dịch</Text></Pressable></View></View>}
    {booking.status === "CONFIRMED" && <View style={styles.paymentSuccess}><Text style={styles.successTitle}>Thanh toán thành công</Text><Text style={styles.successText}>Mã giao dịch {booking.latestPayment?.code ?? "Đang cập nhật"}{"\n"}{money(booking.latestPayment?.amount ?? booking.totalAmount)}</Text></View>}
    {ticket && <View style={styles.ticketCard}><Text style={styles.ticketTitle}>VÉ ĐIỆN TỬ ĐÃ SẴN SÀNG</Text><Text style={styles.ticketMovie}>{ticket.movie.title}</Text><Text style={styles.ticketMeta}>{dateTime(ticket.showtime.startsAt)} · Ghế {ticket.seats.join(", ")}</Text><Link href={`/tickets/${ticket.bookingId}` as Href} asChild><Pressable style={styles.openTicket}><Text style={styles.openTicketText}>Mở vé và mã QR</Text></Pressable></Link></View>}
    {booking.status === "EXPIRED" && <Text style={styles.stateText}>Đơn đã hết hạn và ghế đã được giải phóng.</Text>}
    {booking.status === "CANCELLED" && <Text style={styles.stateText}>Đơn đã được hủy.</Text>}
    {active && <Pressable disabled={submitting} onPress={() => void cancel()}><Text style={styles.cancel}>Hủy đơn</Text></Pressable>}
    {error && <Text style={styles.error}>{error}</Text>}
    {paymentMessage && <Text style={styles.paymentMessage}>{paymentMessage}</Text>}
  </ScrollView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#0D0F17" }, content: { padding: 22, paddingTop: 60, paddingBottom: 44 }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24, backgroundColor: "#0D0F17" },
  eyebrow: { color: "#FF7089", fontSize: 10, fontWeight: "900", letterSpacing: 1.5 }, title: { marginTop: 7, marginBottom: 18, color: "#FFFFFF", fontSize: 30, fontWeight: "900" }, muted: { marginTop: 10, color: "#979BAB" },
  card: { marginBottom: 14, padding: 17, borderRadius: 17, backgroundColor: "#191B27", borderWidth: 1, borderColor: "#292C3A" }, movie: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" }, meta: { marginTop: 6, color: "#C3C6D1", fontSize: 12 }, address: { marginTop: 6, color: "#858A9B", fontSize: 11 },
  sectionTitle: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, seats: { marginTop: 7, marginBottom: 11, color: "#FF8198", fontSize: 20, fontWeight: "900" }, row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 7, borderTopWidth: 1, borderTopColor: "#292C3A" }, rowText: { color: "#AEB2C0", fontSize: 12 },
  optional: { marginTop: 4, marginBottom: 8, color: "#7F8495", fontSize: 10 }, productRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 12, borderTopWidth: 1, borderTopColor: "#292C3A" }, productInfo: { flex: 1, paddingRight: 10 }, productName: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, productDescription: { marginTop: 3, color: "#858A9B", fontSize: 10 }, productPrice: { marginTop: 4, color: "#FF8198", fontSize: 11, fontWeight: "800" }, quantity: { flexDirection: "row", alignItems: "center", gap: 9 }, quantityButton: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 9, backgroundColor: "#2B2E3C" }, quantityButtonText: { color: "#FFFFFF", fontSize: 18, fontWeight: "800" }, quantityValue: { minWidth: 16, color: "#FFFFFF", textAlign: "center", fontWeight: "800" }, saveFood: { alignItems: "center", marginTop: 10, paddingVertical: 11, borderRadius: 12, backgroundColor: "#303446" }, saveFoodText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" },
  voucherForm: { flexDirection: "row", gap: 8, marginTop: 11 }, voucherInput: { flex: 1, paddingHorizontal: 13, paddingVertical: 11, borderRadius: 11, backgroundColor: "#11131C", color: "#FFFFFF", fontSize: 12 }, applyVoucher: { justifyContent: "center", paddingHorizontal: 14, borderRadius: 11, backgroundColor: "#FF526F" }, applyVoucherText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, voucherSuggestions: { gap: 8, paddingTop: 11 }, voucherChip: { minWidth: 96, padding: 10, borderRadius: 11, backgroundColor: "#242735" }, voucherChipCode: { color: "#FF8198", fontSize: 11, fontWeight: "900" }, voucherChipHint: { marginTop: 3, color: "#858A9B", fontSize: 9 }, appliedVoucher: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 10, padding: 12, borderRadius: 12, backgroundColor: "#18271F" }, voucherCode: { color: "#7BE6A1", fontSize: 13, fontWeight: "900" }, removeVoucher: { color: "#FF91A5", fontSize: 11, fontWeight: "800" },
  mockActions: { flexDirection: "row", gap: 9, marginTop: 9 }, mockSecondary: { flex: 1, alignItems: "center", paddingVertical: 11, borderRadius: 11, backgroundColor: "#2B2E3C" }, mockSecondaryText: { color: "#C7CAD5", fontSize: 11, fontWeight: "800" }, paymentSuccess: { alignItems: "center", marginTop: 18, padding: 20, borderRadius: 17, backgroundColor: "#18271F", borderWidth: 1, borderColor: "#2F7049" }, paymentMessage: { marginTop: 12, color: "#F1C77A", textAlign: "center", fontWeight: "700" },
  priceRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: "#292C3A" }, priceLabel: { color: "#AEB2C0", fontSize: 12 }, priceValue: { color: "#D7D9E2", fontSize: 12, fontWeight: "700" }, discount: { color: "#75D99A", fontSize: 12, fontWeight: "800" }, totalCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 5, paddingTop: 14 }, totalLabel: { color: "#FFFFFF", fontWeight: "800" }, total: { color: "#FF7089", fontSize: 22, fontWeight: "900" },
  timer: { alignItems: "center", marginTop: 18 }, timerLabel: { color: "#9297A8", fontSize: 11 }, timerValue: { marginTop: 3, color: "#FF7089", fontSize: 28, fontWeight: "900" }, primary: { minHeight: 52, alignItems: "center", justifyContent: "center", marginTop: 18, borderRadius: 15, backgroundColor: "#FF526F" }, primaryText: { color: "#FFFFFF", fontWeight: "900" },
  success: { alignItems: "center", marginTop: 18, padding: 18, borderRadius: 16, backgroundColor: "#18271F", borderWidth: 1, borderColor: "#285A3C" }, successTitle: { color: "#7BE6A1", fontSize: 17, fontWeight: "900" }, successText: { marginTop: 7, color: "#B7C9BE", textAlign: "center", lineHeight: 20 }, stateText: { marginTop: 18, color: "#C7CAD5", textAlign: "center" }, cancel: { marginTop: 18, color: "#FF91A5", textAlign: "center", fontWeight: "800" }, error: { marginTop: 14, color: "#FF8599", textAlign: "center" }, retry: { marginTop: 16, color: "#FF7089", fontWeight: "800" },
  ticketCard: { alignItems: "center", marginTop: 14, padding: 20, borderRadius: 18, backgroundColor: "#191B27", borderWidth: 1, borderColor: "#FF526F" }, ticketTitle: { color: "#FF8198", fontSize: 12, fontWeight: "900", letterSpacing: 1.5 }, ticketMovie: { marginTop: 12, color: "#FFFFFF", fontSize: 18, fontWeight: "900", textAlign: "center" }, ticketMeta: { marginTop: 7, color: "#BFC2CE", fontSize: 12, textAlign: "center" }, openTicket: { marginTop: 16, paddingHorizontal: 24, paddingVertical: 13, borderRadius: 13, backgroundColor: "#FF526F" }, openTicketText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" },
});
