import type { NextFunction, Request, Response } from "express";
import { applyBookingVoucher, getBooking, holdSeats, HoldConflictError, HoldNotFoundError, HoldValidationError, listBookingHistory, parseBookingId, releaseHold, removeBookingVoucher, submitBooking, updateBookingConcessions } from "./booking.service.js";
function handle(error: unknown, response: Response) { if (error instanceof HoldValidationError) { response.status(400).json({ error: { code: "VALIDATION_ERROR", message: error.message } }); return true; } if (error instanceof HoldConflictError) { response.status(409).json({ error: { code: "HOLD_CONFLICT", message: error.message } }); return true; } if (error instanceof HoldNotFoundError) { response.status(404).json({ error: { code: "HOLD_NOT_FOUND", message: error.message } }); return true; } return false; }
export async function holdSeatsHandler(req: Request, res: Response, next: NextFunction) { try { const booking = await holdSeats(res.locals.auth.userId as number, String(req.params.id), req.body); res.location(`/api/v1/bookings/${booking.id}`).status(201).json({ data: booking }); } catch (error) { if (!handle(error, res)) next(error); } }
export async function releaseHoldHandler(req: Request, res: Response, next: NextFunction) { try { await releaseHold(parseBookingId(String(req.params.id)), res.locals.auth.userId as number); res.status(204).send(); } catch (error) { if (!handle(error, res)) next(error); } }
export async function getBookingHandler(req: Request, res: Response, next: NextFunction) { try { res.json({ data: await getBooking(parseBookingId(String(req.params.id)), res.locals.auth.userId as number) }); } catch (error) { if (!handle(error, res)) next(error); } }
export async function submitBookingHandler(req: Request, res: Response, next: NextFunction) { try { res.json({ data: await submitBooking(parseBookingId(String(req.params.id)), res.locals.auth.userId as number) }); } catch (error) { if (!handle(error, res)) next(error); } }
export async function updateBookingConcessionsHandler(req: Request, res: Response, next: NextFunction) { try { res.json({ data: await updateBookingConcessions(parseBookingId(String(req.params.id)), res.locals.auth.userId as number, req.body) }); } catch (error) { if (!handle(error, res)) next(error); } }
export async function applyBookingVoucherHandler(req: Request, res: Response, next: NextFunction) { try { res.json({ data: await applyBookingVoucher(parseBookingId(String(req.params.id)), res.locals.auth.userId as number, req.body) }); } catch (error) { if (!handle(error, res)) next(error); } }
export async function removeBookingVoucherHandler(req: Request, res: Response, next: NextFunction) { try { res.json({ data: await removeBookingVoucher(parseBookingId(String(req.params.id)), res.locals.auth.userId as number) }); } catch (error) { if (!handle(error, res)) next(error); } }
export async function listBookingHistoryHandler(req: Request, res: Response, next: NextFunction) { try { res.json(await listBookingHistory(res.locals.auth.userId as number, req.query as Record<string, unknown>)); } catch (error) { if (!handle(error, res)) next(error); } }
