import { Router } from "express";
import { requireAuthentication } from "../auth/auth.middleware.js";
import { applyBookingVoucherHandler, getBookingHandler, listBookingHistoryHandler, releaseHoldHandler, removeBookingVoucherHandler, submitBookingHandler, updateBookingConcessionsHandler } from "./booking.controller.js";
import { payMockHandler } from "../payments/payment.controller.js";
import { getTicketHandler } from "../tickets/ticket.controller.js";
import { validateRequest } from "../../validation/request-validation.js";
import { bookingSchemas, idParams } from "../../validation/schemas.js";
export const bookingRouter = Router();
bookingRouter.get("/", requireAuthentication, validateRequest({ query: bookingSchemas.historyQuery }), listBookingHistoryHandler);
bookingRouter.get("/:id", requireAuthentication, validateRequest({ params: idParams() }), getBookingHandler);
bookingRouter.post("/:id/submit", requireAuthentication, validateRequest({ params: idParams() }), submitBookingHandler);
bookingRouter.put("/:id/concessions", requireAuthentication, validateRequest({ params: idParams(), body: bookingSchemas.concessions }), updateBookingConcessionsHandler);
bookingRouter.put("/:id/voucher", requireAuthentication, validateRequest({ params: idParams(), body: bookingSchemas.voucher }), applyBookingVoucherHandler);
bookingRouter.delete("/:id/voucher", requireAuthentication, validateRequest({ params: idParams() }), removeBookingVoucherHandler);
bookingRouter.post("/:id/payments/mock", requireAuthentication, validateRequest({ params: idParams(), body: bookingSchemas.payment }), payMockHandler);
bookingRouter.get("/:id/ticket", requireAuthentication, validateRequest({ params: idParams() }), getTicketHandler);
bookingRouter.delete("/:id/hold", requireAuthentication, validateRequest({ params: idParams() }), releaseHoldHandler);
